#Application Config
application:
  listino: 1
  sconto: 0

spring:
# ==============================================================
# = Cloud Parameteres
# ==============================================================
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
# ==============================================================
# = ZipKin parameters
# ==============================================================
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
      #type: rabbit 
# ==============================================================
# = Sleuth parameters
# ==============================================================
  sleuth:
    sampler:
      probability: 1.0
    traceId128: false
# ==============================================================
# = Proprietà RabbitMQ
# ==============================================================      
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: rabbitmq

# ==============================================================
# = Actuator Parameters
# Metodo POST con url: /actuator/refresh
# Metodo POST con url: /actuator/bus-refresh 
# ==============================================================
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,bus-refresh,hystrix.stream
# ==============================================================
# = Actuator Info
# ==============================================================
info:
  assistenza:
    nome: "Nicola La Rocca"
  nome:
    nome-app: "PriceArt Web Service"
  profilo: "Standard Con Sconto"
                
# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    root: INFO
    org.springframework.cloud: ERROR

# ==============================================================
# = Proprietà Servizio gestUser
# ==============================================================           
#gestuser:
#  password: BimBumBam_2018
#  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
#  userId: ReadUser

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
#sicurezza:
#    uri: /auth
#    refresh: /refresh
#    header: Authorization
#    prefix: Bearer 
#    expiration: 86400
#    secret: 123_Stella

