#==========================================================
#= PriceArt Web Service - Versione Base
#==========================================================
server:
  port: 5071
 
spring:
  profiles:
    active: list1
  application:
    name: PriceArtService
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/Alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org-springframework-security: DEBUG

# ==============================================================
# = Parametri Sicurezza OAUTH2 con KeyCloack - /auth
# ==============================================================
keycloak:
  auth-server-url: http://localhost:8080
  realm: Alphashop
  resource: PriceArtService
  public-client: true 
